plugins: [jekyll-paginate, jekyll-sitemap]
excerpt_separator: ""
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
url: https://gaevoy.com
url_for_disqus: https://gaevoy.com
title: Vladimir Gaevoy
email: 
author: Vladimir Gaevoy
description: My awesome blog
paginate: 16
paginate_path: "page:num"
