excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gaevoy.github.io
title: webdev
email: 
author: Vladimir Gaevoy
description: My awesome new site
paginate: 3
google_analytics: UA-73040051-1
