gems: [jekyll-paginate]
excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://gaevoy.github.io
title: Vladimir Gaevoy
email: 
author: Vladimir Gaevoy
description: My awesome new site
paginate: 5
paginate_path: "page:num"
google_analytics: UA-73040051-1
