plugins: [jekyll-paginate]
excerpt_separator: ""
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
url: https://gaevoy.github.io
title: Vladimir Gaevoy blog
email: 
author: Vladimir Gaevoy
description: My awesome blog
paginate: 5
paginate_path: "page:num"
google_analytics: UA-73040051-1
